### ISSUE TITLE
Can't find variable: console_reporter 

### ISSUE THREAD

**Issue by herry1234** [jcarver989/phantom-jasmine#2]
i guess the issue is on  this line, but i don't know how to fix it.

 get_status: ->
   @page.evaluate(-> console_reporter.status)

ReferenceError: Can't find variable: console_reporter

  phantomjs://webpage.evaluate():2
  phantomjs://webpage.evaluate():3
  phantomjs://webpage.evaluate():3

**Comment by jcarver989** [comment]
Which version of PhantomJS are you using? I've tested this on  1.4.1 and  just upgraded to 1.6.0 (latest) and haven't had any issues.

**Comment by mamoo** [comment]
This happened also to me.
I'm using require.js to load tested modules, and also jasmine. 
Since console_reporter is not defined in the page scope the script will complain. 
A workaround is to assign console_reporter to the window object directly using:

``` javascript
require(['underscore', 'jasmine-html', 'jasmine-consolerunner'], function (_, jasmine) {
    var jasmineEnv = jasmine.getEnv();

    [...]
    var console_reporter = new jasmine.ConsoleReporter();
    window.console_reporter = console_reporter; // <<< Add console_reporter to the window object

    jasmineEnv.addReporter(htmlReporter);
    jasmineEnv.addReporter(console_reporter);
    [...]
```

**Comment by ignacio-valdivieso** [comment]
@mamoo thank you! :tangerine:
