### ISSUE TITLE
Javascript exceptions are not printed to console

### ISSUE THREAD

**Issue by Vanuan** [jcarver989/phantom-jasmine#4]
When I have a js error like `object  has no method` in the browser I don't see it in console.
I only see `[object Object]`

**Comment by Vanuan** [comment]
probably, not a problem of phantom-jasmine:

http://code.google.com/p/phantomjs/issues/detail?id=166

**Comment by Vanuan** [comment]
Fixed with the commit above and phantomjs 1.6

**Comment by jcarver989** [comment]
Merged, thanks!
